import type { Manifest } from "../types";

// Small synthetic manifest for unit tests. Keep it minimal — add only what
// the tests under test actually look at.
export function makeManifest(overrides: Partial<Manifest> = {}): Manifest {
  return {
    exported_at: "2026-04-19T12:00:00",
    event_types: ["dialogue", "newspaper", "notification"],
    triggers: ["character_arrived", "unique_placed", "manual"],
    buckets: ["residential", "commercial", "industrial"],
    categories: ["road", "nature", "generic", "unique"],
    character_states: [
      "NOT_ARRIVED",
      "ARRIVED",
      "WANT_REVEALED",
      "SATISFIED",
      "CONTRIBUTES_TO_LANDMARK",
    ],
    patron_states: ["LOCKED", "LANDMARK_AVAILABLE", "COMPLETED"],
    characters: [
      {
        character_id: "aristocrat_commercial",
        display_name: "Lord Ashworth",
        bio: "Old money.",
        patron_id: "aristocrat",
        associated_bucket: "commercial",
        arrival_threshold: 10,
        arrival_requires_tier: 1,
        want_building_id: "building_members_club",
        portrait: "",
        _path: "res://data/characters/aristocrat_commercial.json",
      },
      {
        character_id: "aristocrat_industrial",
        display_name: "Industrial Lord",
        bio: "",
        patron_id: "aristocrat",
        associated_bucket: "industrial",
        arrival_threshold: 10,
        arrival_requires_tier: 1,
        want_building_id: "building_brewery",
        portrait: "",
        _path: "res://data/characters/aristocrat_industrial.json",
      },
      {
        character_id: "aristocrat_residential",
        display_name: "Residential Lord",
        bio: "",
        patron_id: "aristocrat",
        associated_bucket: "residential",
        arrival_threshold: 10,
        arrival_requires_tier: 1,
        want_building_id: "building_mansion",
        portrait: "",
        _path: "res://data/characters/aristocrat_residential.json",
      },
    ],
    patrons: [
      {
        patron_id: "aristocrat",
        display_name: "Lord Ashworth's Circle",
        bio: "Aristocrats.",
        character_ids: [
          "aristocrat_commercial",
          "aristocrat_industrial",
          "aristocrat_residential",
        ],
        landmark_building_id: "building_theatre",
        portrait: "",
        donation_area: { shape: "rect", rect: [8, -8, 12, 16] },
        _path: "res://data/patrons/aristocrat.json",
      },
    ],
    buildings: [
      {
        building_id: "building_members_club",
        display_name: "Members Club",
        category: "unique",
        pool_id: "",
        model_path: "",
        chain_role: "want",
        patron_id: "aristocrat",
        character_id: "aristocrat_commercial",
        bucket: "commercial",
        tier: 0,
        _path: "res://data/buildings/unique/building_members_club.json",
        body: {
          building_id: "building_members_club",
          display_name: "Members Club",
          description: "",
          model_path: "",
          model_scale: 1,
          model_offset: [0, 0, 0],
          model_rotation_y: 0,
          footprint: [[0, 0]],
          category: "unique",
          profiles: [],
          tags: [],
        },
      },
      {
        building_id: "building_brewery",
        display_name: "Brewery",
        category: "unique",
        pool_id: "",
        model_path: "",
        chain_role: "want",
        patron_id: "aristocrat",
        character_id: "aristocrat_industrial",
        bucket: "industrial",
        tier: 0,
        _path: "res://data/buildings/unique/building_brewery.json",
        body: {
          building_id: "building_brewery",
          display_name: "Brewery",
          description: "",
          model_path: "",
          model_scale: 1,
          model_offset: [0, 0, 0],
          model_rotation_y: 0,
          footprint: [[0, 0]],
          category: "unique",
          profiles: [],
          tags: [],
        },
      },
      {
        building_id: "building_mansion",
        display_name: "Mansion",
        category: "unique",
        pool_id: "",
        model_path: "",
        chain_role: "want",
        patron_id: "aristocrat",
        character_id: "aristocrat_residential",
        bucket: "residential",
        tier: 0,
        _path: "res://data/buildings/unique/building_mansion.json",
        body: {
          building_id: "building_mansion",
          display_name: "Mansion",
          description: "",
          model_path: "",
          model_scale: 1,
          model_offset: [0, 0, 0],
          model_rotation_y: 0,
          footprint: [[0, 0]],
          category: "unique",
          profiles: [],
          tags: [],
        },
      },
      {
        building_id: "building_theatre",
        display_name: "The Theatre",
        category: "unique",
        pool_id: "",
        model_path: "",
        chain_role: "landmark",
        patron_id: "aristocrat",
        character_id: "",
        bucket: "residential",
        tier: 0,
        _path: "res://data/buildings/unique/building_theatre.json",
        body: {
          building_id: "building_theatre",
          display_name: "The Theatre",
          description: "",
          model_path: "",
          model_scale: 1,
          model_offset: [0, 0, 0],
          model_rotation_y: 0,
          footprint: [[0, 0]],
          category: "unique",
          profiles: [],
          tags: [],
        },
      },
    ],
    events: [
      {
        event_id: "aristocrat_commercial_arrival",
        event_type: "dialogue",
        trigger_event: "character_arrived",
        trigger_character_id: "aristocrat_commercial",
        trigger_patron_id: "",
        trigger_building_id: "",
        enabled_if: "",
        category: "characters",
        _path: "res://data/events/characters/aristocrat_commercial/arrival.json",
        body: {
          event_id: "aristocrat_commercial_arrival",
          event_type: "dialogue",
          trigger: {
            event: "character_arrived",
            character_id: "aristocrat_commercial",
          },
          enabled_if: "",
          payload: {
            tree_id: "aristocrat_commercial_arrival_tree",
            entry_node_id: "n_start",
            nodes: [
              {
                node_id: "n_start",
                speaker: "",
                body: "Welcome.",
                on_enter: [],
                options: [
                  { label: "Continue", next: "n_end", effects: [] },
                ],
              },
              {
                node_id: "n_end",
                speaker: "",
                body: "Bye.",
                on_enter: [],
                options: [
                  {
                    label: "Close",
                    next: "",
                    effects: [{ kind: "set_flag", target: "met_aristocrat_commercial" }],
                  },
                ],
              },
            ],
          },
        },
      },
    ],
    flags: ["met_aristocrat_commercial"],
    ...overrides,
  };
}
