import { create } from "zustand";
import type { CharacterDoc, Manifest, ManifestCharacter, ManifestPatron, PatronDoc } from "./types";
import type { Repo } from "./fs/repo";
import { pickRepoRoot, restoreRepoRoot } from "./fs/fsaRepo";
import { loadManifestFromFile } from "./fs/downloadRepo";
import { pathFromRes } from "./events/paths";

export type Tab = "characters" | "patrons" | "events" | "buildings";

interface AppState {
  repo: Repo | null;
  manifest: Manifest | null;
  loading: boolean;
  error: string | null;
  activeTab: Tab;

  setTab: (t: Tab) => void;
  connectFsa: () => Promise<void>;
  connectDownload: (file: File) => Promise<void>;
  tryRestoreRepo: () => Promise<void>;
  reloadManifest: () => Promise<void>;
  writeJson: (relPath: string[], payload: unknown) => Promise<void>;
  // Splice the just-saved doc into manifest.* and persist the manifest back
  // to disk. Godot's editor plugin still owns _manifest.json conceptually
  // (its exporter produces the same shape), but writing it on every save
  // means the SPA stays self-consistent across refreshes — the manifest no
  // longer goes stale relative to the per-entity JSONs.
  patchCharacter: (doc: CharacterDoc) => Promise<void>;
  patchPatron: (doc: PatronDoc) => Promise<void>;
}

const MANIFEST_RELPATH = ["data", "events", "_manifest.json"];

export const useApp = create<AppState>((set, get) => ({
  repo: null,
  manifest: null,
  loading: false,
  error: null,
  activeTab: "characters",

  setTab: (t) => set({ activeTab: t }),

  connectFsa: async () => {
    set({ loading: true, error: null });
    try {
      const repo = await pickRepoRoot();
      set({ repo });
      await get().reloadManifest();
    } catch (e) {
      set({ error: (e as Error).message });
    } finally {
      set({ loading: false });
    }
  },

  connectDownload: async (file: File) => {
    set({ loading: true, error: null });
    try {
      const repo = await loadManifestFromFile(file);
      const manifest = await repo.readManifest();
      set({ repo, manifest });
    } catch (e) {
      set({ error: `Could not parse ${file.name} — ${(e as Error).message}` });
    } finally {
      set({ loading: false });
    }
  },

  tryRestoreRepo: async () => {
    try {
      const repo = await restoreRepoRoot();
      if (repo) {
        set({ repo });
        await get().reloadManifest();
      }
    } catch {
      // no-op — user will click Connect
    }
  },

  reloadManifest: async () => {
    const repo = get().repo;
    if (!repo) return;
    set({ loading: true, error: null });
    try {
      const manifest = await repo.readManifest();
      // The cached manifest is regenerated by Godot's editor plugin, not by
      // the web editor. After any web-side save it's stale until the user
      // re-runs Export. To keep the form honest across refreshes we re-read
      // each character / patron JSON directly from disk and merge over the
      // manifest entry. FSA only — download mode has no per-file access.
      if (repo.readJson) {
        await Promise.all([
          ...manifest.characters.map(async (c, i) => {
            try {
              const fresh = (await repo.readJson!(pathFromRes(c._path))) as Partial<ManifestCharacter>;
              manifest.characters[i] = { ...c, ...fresh };
            } catch {
              // file might be missing if the manifest is ahead of the
              // working tree — keep the manifest entry as fallback.
            }
          }),
          ...manifest.patrons.map(async (p, i) => {
            try {
              const fresh = (await repo.readJson!(pathFromRes(p._path))) as Partial<ManifestPatron>;
              manifest.patrons[i] = { ...p, ...fresh };
            } catch {
              // see above
            }
          }),
        ]);
      }
      set({ manifest });
    } catch (e) {
      set({ error: `Could not load manifest — run Export in Godot first. (${(e as Error).message})` });
    } finally {
      set({ loading: false });
    }
  },

  writeJson: async (relPath, payload) => {
    const repo = get().repo;
    if (!repo) throw new Error("Not connected to a repo");
    await repo.writeJson(relPath, JSON.stringify(payload, null, 2) + "\n");
  },

  patchCharacter: async (doc) => {
    const m = get().manifest;
    if (!m) return;
    const existing = m.characters.find((c) => c.character_id === doc.character_id);
    const entry: ManifestCharacter = {
      ...doc,
      _path: existing?._path ?? `res://data/characters/${doc.character_id}.json`,
    };
    const others = m.characters.filter((c) => c.character_id !== doc.character_id);
    const next: Manifest = { ...m, characters: [...others, entry] };
    set({ manifest: next });
    await persistManifest(get().repo, next);
  },

  patchPatron: async (doc) => {
    const m = get().manifest;
    if (!m) return;
    const existing = m.patrons.find((p) => p.patron_id === doc.patron_id);
    const entry: ManifestPatron = {
      ...doc,
      _path: existing?._path ?? `res://data/patrons/${doc.patron_id}.json`,
    };
    const others = m.patrons.filter((p) => p.patron_id !== doc.patron_id);
    const next: Manifest = { ...m, patrons: [...others, entry] };
    set({ manifest: next });
    await persistManifest(get().repo, next);
  },
}));

async function persistManifest(repo: Repo | null, manifest: Manifest): Promise<void> {
  if (!repo) return;
  try {
    const stamped: Manifest = {
      ...manifest,
      exported_at: new Date().toISOString(),
    };
    await repo.writeJson(MANIFEST_RELPATH, JSON.stringify(stamped, null, 2) + "\n");
  } catch (e) {
    console.warn("[store] could not persist manifest", e);
  }
}
